version: '3.8'

services:
  jarvis-backend:
    build:
      context: ./src
    ports:
      - "3000:3000"
    depends_on:
      - jarvis-backtest

  jarvis-backtest:
    build:
      context: ../jarvis-backtest
    ports:
      - "3001:3001"
